name: EnvironmentExample
on: workflow_dispatch
jobs: 
  Dev-Deployment-Job:
    name:DevDeployment
    runs-on:ubuntu-latest
    evironment:Development
    steps:
      - shell: bash
        run: |
          echo ${{ vars.DemoVar }}
  Prod-Deployment-Job:
    name: ProdDeployment
    runs-on: ubuntu-latest
    environment: Production
    steps: 
      - shell: bash
        run: |
          echo ${{ vars.DemoVar }}
